# Examples of Predictions
All the issues used in this notebook, are actual issues from Thoth's [kebechet repo](https://github.com/thoth-station/kebechet). 

In [1]:
import numpy as np
import pandas as pd

from Label_Bot.label_bot import utils, models

## Init both models for comparison

In [2]:
bot_with_head = models.Bot(model_path='trained_models/roberta-base')
bot_no_head = models.Bot(use_head=False, model_path='trained_models/roberta-base')

### True Label: Enhancement

In [3]:
title = "Possibility to specify a branch to be used for the release"

body = "\
Is your feature request related to a problem? Please describe.\
As a maintainer of a project which potentially has many contributors and possibly other maintainers as well,\
I want to be able to specify a branch which should be used for the release so that I did not run into a scenario when I request a release and before the actual release is created, my master gets corrupted because of a flawed PR.\
Describe the solution you'd like\
I want to be able to specify for example stable branch to be used for the release. I suppose this can be part of the configuration so that I set the 'release' branch only once.\
"

In [4]:
bot_no_head.predict(title, body)

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

array([[0.01371483, 0.15727586, 0.36711872]], dtype=float32)

In [5]:
bot_with_head.predict(title, body)

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

array([[0.05977056, 0.15493096, 0.7981587 ]], dtype=float32)

### True Label: Question

In [20]:
title = "Adding OpenDataHub projects"

body = "\
They seem to have so many repositories under one repository, how do we support it?\
I dont think, we do support nested repo's.\
https://gitlab.com/opendatahub/ai-library/-/tree/master/flakes_train\
"

In [12]:
bot_no_head.predict(title, body)

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

array([[0.00692506, 0.20943904, 0.32344556]], dtype=float32)

In [13]:
bot_with_head.predict(title, body)

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

array([[0.01671544, 0.8998082 , 0.10957056]], dtype=float32)

### True Label: Bug

In [21]:
title = "Kebechet dependency update should not check PyPI but Thoth Knowledge Graph"

body = "\
Describe the bug\
Kebechet updates are not checking Thoth, therefore when the dependency is updated from PyPI and the PR is merged, s2i build using Thoth and only the Pipfile will not find the most updated version of that package just released because it has not been solved yet. Adviser relies on Thoth Knowledge Graph for Solved Python Packages.\
Therefore micropipenv will use Adviser suggestions and the build created in test environment won't have the latest version (e.g. graph-sync-job dependency updated when thoth-storages is updated)\
Expected behavior\
Kebechet trusts Thoth, which should have package release job run more often so that graph refresh job can solve those packages faster and therefore having s2i build using Thoth that actually have the latest version (e.g. graph-sync-job would not get the latest thoth-common released until the next day because that is when we run again package release job and after that solver for that package)\
Additional context\
package release job https://github.com/thoth-station/package-releases-job\
graph refresh job https://github.com/thoth-station/graph-refresh-job\
"

In [18]:
bot_no_head.predict(title, body)

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

array([[0.8097753 , 0.04235939, 0.17039804]], dtype=float32)

In [19]:
bot_with_head.predict(title, body)

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

array([[0.8955525 , 0.06042087, 0.23431641]], dtype=float32)